version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    env_file: .env
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"  # Adjust based on your backend configuration
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    env_file: .env
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"  # Expose port 3000 for the frontend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"  # Expose port 80 for web traffic
    depends_on:
      - backend
      - frontend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username  # Change this to your desired username
      POSTGRES_PASSWORD: your_password  # Change this to your desired password
      POSTGRES_DB: your_database  # Change this to your desired database name
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: