# Use the official Node.js image as the base image
FROM node:16.20.2-alpine

# Set the working directory
WORKDIR /frontend

# Copy the frontend files
COPY frontend/package.json frontend/yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the frontend files
COPY frontend/src ./src

# Build the frontend application
RUN yarn build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["yarn", "start"]
