version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend

  server:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend

  networks:
    production-networks:
      name: bind
      external: true