# Use Node.js base image for build
FROM node:18-alpine as build

# Set the working directory
WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install dependencies using Yarn
RUN yarn install

# Copy the frontend project
COPY . .

# Build the frontend
RUN yarn build

# Use Nginx to serve the frontend
FROM nginx:alpine

# Copy build files to Nginx's html directory
COPY --from=build /app/dist /usr/share/nginx/html

# Expose Nginx default port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
