version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:3000"  # Change the host port as needed
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"  # Change the host port as needed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge