version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile-backend
    container_name: backend-service
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=database-service
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydatabase
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile-frontend
    container_name: frontend-service
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: ../Dockerfile-nginx
    container_name: nginx-service
    ports:
      - "8080:80" # Changed host port to 8080 to avoid conflicts
    depends_on:
      - frontend
      - backend

  database:
    image: postgres:latest
    container_name: database-service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
