version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-backend
    volumes:
      - ./backend:/backend
    ports:
      - "5000:5000"
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"

networks:
  default:
    name: bind