# Use Nginx as the base image
FROM nginx:alpine

# Copy custom Nginx configuration
COPY vhost.template /etc/nginx/conf.d/default.conf
COPY entrypoint-nginx.sh /entrypoint.sh

# Make the script executable
RUN chmod +x /entrypoint.sh

# Expose Nginx port
EXPOSE 80

# Start the custom Nginx entrypoint script
CMD ["/entrypoint.sh"]
