# Use Nginx as the base image
FROM nginx:alpine

# Copy custom Nginx configuration
COPY nginx/vhost.template /etc/nginx/conf.d/default.conf

# Expose Nginx port
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]