version: '3.8'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - default

networks:
  default:
    driver: bridge