# Use a Node.js base image
FROM node:16.20.2-alpine

# Set the working directory
WORKDIR /backend

# Pass the environment file via build argument
ARG ENV_FILE=./backend/.env.example

# Copy necessary files
COPY backend/package.json backend/yarn.lock ./
COPY ${ENV_FILE} /backend/.env

# Install dependencies
RUN yarn install

# Copy the rest of the application files
COPY backend/src ./src
COPY backend/upload ./upload

# Expose the application's port
EXPOSE 3000

# Start the application
CMD ["yarn", "start"]