name: Automate Re-deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH remote to Contabo VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 212.28.178.254
          username: root
          key: ${{ secrets.CONTABO_KEY }}
          port: 22
          script: |
            cd dev-ops-ass
            git pull
            . ~/.nvm/nvm.sh
            #docker compose down
            #docker composer build
            #docker compose up -d