name: Automate Re-deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH remote to Contabo VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 212.28.178.254
          username: root
          key: ${{ secrets.CONTABO_KEY }}
          port: 22
          script: |
            cd dev-ops-ass
            git fetch
            if [ "$(git rev-parse HEAD)" != "$(git rev-parse @{u})" ]; then
              echo "Changes detected. Pulling updates..."
              git pull
              git submodule update --init --recursive

              . ~/.nvm/nvm.sh
              nvm install 16
              nvm use 16

              echo "Building updated containers..."
              docker compose build --pull

              echo "Applying updates to running containers..."
              docker compose up -d --no-deps --build
            else
              echo "No changes detected. Skipping redeployment."
            fi